NODE_COUNT=3


Vagrant.configure("2") do |config| #"2" is Configuration Version
 config.vm.box = "centos/7"
 config.vm.define "master" do |master|
  master.vm.hostname = "HTcondor-master.intranet.local"
  master.vm.network "private_network", ip: "192.168.10.3", name: "vboxnet1"
  master.vm.network "forwarded_port", guest: 22, host:2222
   master.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", "HTCondor-Master"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--memory", "2048"]	
  end
 end





NODE_COUNT.times do |i|
node_id = "node#{i+1}"
ip_address = "192.168.10.#{i+4}"
config.vm.define "node#{i+1}" do |node|
 node.vm.hostname = "#{node_id}.intranet.local"
 node.vm.network "private_network", ip: "#{ip_address}", name: "vboxnet1"
 node.vm.network "forwarded_port", guest: 22, host: "#{i+2223}"
  node.vm.provider "virtualbox" do |v|
   v.customize ["modifyvm", :id, "--name", "HTCondor-node#{i+1}"]
   v.customize ["modifyvm", :id, "--cpus", "2"]
   v.customize ["modifyvm", :id, "--memory", "2048"]
   end
  end
 end
end
